# Generated by Django 3.2.5 on 2022-01-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_newuser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='department',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
