# Generated by Django 3.0 on 2021-11-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
