# Generated by Django 3.0 on 2021-11-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventregistration_is_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventinfo',
            name='days',
        ),
        migrations.RemoveField(
            model_name='eventinfo',
            name='event_date',
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='reg_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
