# Generated by Django 3.0 on 2021-11-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20211128_1056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventinfo',
            options={'ordering': ['start_date']},
        ),
        migrations.AddField(
            model_name='eventinfo',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='eventinfo',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
