# Generated by Django 3.2.5 on 2021-12-18 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventinfo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='student_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
